CREATE TABLE IF NOT EXISTS public.organization (
    organization_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description text NOT NULL,
    contact_email varchar(100) NOT NULL,
    logo_filename varchar(100) NOT NULL
);

INSERT INTO public.organization (
    organization_id,
    name,
    description,
    contact_email,
    logo_filename
) VALUES
    (
        1,
        'BrightFuture Builders',
        'A nonprofit focused on improving community infrastructure through sustainable construction projects.',
        'info@brightfuturebuilders.org',
        'brightfuture-logo.png'
    ),
    (
        2,
        'GreenHarvest Growers',
        'An urban farming collective promoting food sustainability and education in local neighborhoods.',
        'contact@greenharvest.org',
        'greenharvest-logo.png'
    ),
    (
        3,
        'UnityServe Volunteers',
        'A volunteer coordination group supporting local charities and service initiatives.',
        'hello@unityserve.org',
        'unityserve-logo.png'
    )
ON CONFLICT (organization_id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    contact_email = EXCLUDED.contact_email,
    logo_filename = EXCLUDED.logo_filename;

SELECT setval(
    pg_get_serial_sequence('public.organization', 'organization_id'),
    COALESCE((SELECT MAX(organization_id) FROM public.organization), 1)
);

CREATE TABLE IF NOT EXISTS public.project (
    project_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id integer NOT NULL,
    title varchar(100) NOT NULL,
    description text NOT NULL,
    location varchar(150) NOT NULL,
    project_date date NOT NULL,
    CONSTRAINT project_organization_fk
        FOREIGN KEY (organization_id)
        REFERENCES public.organization (organization_id),
    CONSTRAINT project_organization_title_unique
        UNIQUE (organization_id, title)
);

INSERT INTO public.project (
    organization_id,
    title,
    description,
    location,
    project_date
) VALUES
    (
        1,
        'Community Center Painting',
        'Paint interior rooms and refresh common areas at the neighborhood community center.',
        'Rexburg Community Center',
        '2026-07-18'
    ),
    (
        1,
        'Senior Home Ramp Build',
        'Build an accessibility ramp for a local senior resident.',
        'North Rexburg',
        '2026-08-01'
    ),
    (
        1,
        'Playground Repair Day',
        'Repair benches, tighten equipment hardware, and spread new playground mulch.',
        'Porter Park',
        '2026-08-15'
    ),
    (
        1,
        'Shelter Storage Shelves',
        'Construct sturdy shelving for donated goods at the family shelter.',
        'Madison Family Shelter',
        '2026-09-05'
    ),
    (
        1,
        'Trail Kiosk Installation',
        'Install information kiosks and trail markers along a community walking path.',
        'Teton River Trail',
        '2026-09-19'
    ),
    (
        2,
        'Neighborhood Garden Prep',
        'Prepare planting beds, mix compost, and organize tools for the growing season.',
        'Eastside Community Garden',
        '2026-07-22'
    ),
    (
        2,
        'Harvest Box Assembly',
        'Pack fresh produce boxes for families served by local food pantries.',
        'GreenHarvest Warehouse',
        '2026-08-06'
    ),
    (
        2,
        'School Garden Workshop',
        'Help students plant vegetables and learn basic garden maintenance.',
        'Lincoln Elementary School',
        '2026-08-20'
    ),
    (
        2,
        'Compost Education Booth',
        'Staff an information booth about home composting and waste reduction.',
        'Rexburg Farmers Market',
        '2026-09-10'
    ),
    (
        2,
        'Orchard Gleaning Morning',
        'Pick surplus fruit from a local orchard for donation to food banks.',
        'Sunny Slope Orchard',
        '2026-09-24'
    ),
    (
        3,
        'Food Pantry Sorting',
        'Sort donated cans, check dates, and restock pantry shelves.',
        'Madison County Food Bank',
        '2026-07-25'
    ),
    (
        3,
        'Backpack Supply Drive',
        'Assemble backpacks with school supplies for students in need.',
        'UnityServe Office',
        '2026-08-08'
    ),
    (
        3,
        'Community Tutoring Night',
        'Support students with math, reading, and study skills during an evening tutoring session.',
        'Rexburg Library',
        '2026-08-27'
    ),
    (
        3,
        'Charity 5K Volunteer Crew',
        'Help with check-in, water stations, and route guidance for a charity race.',
        'Smith Park',
        '2026-09-12'
    ),
    (
        3,
        'Winter Clothing Collection',
        'Collect, sort, and label coats, hats, and gloves for distribution.',
        'Madison High School',
        '2026-09-26'
    )
ON CONFLICT (organization_id, title) DO UPDATE SET
    description = EXCLUDED.description,
    location = EXCLUDED.location,
    project_date = EXCLUDED.project_date;

CREATE TABLE IF NOT EXISTS public.category (
    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

INSERT INTO public.category (
    name
) VALUES
    ('Community Support'),
    ('Construction'),
    ('Education'),
    ('Environment'),
    ('Food Security')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.project_category (
    project_id integer NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT project_category_pk
        PRIMARY KEY (project_id, category_id),
    CONSTRAINT project_category_project_fk
        FOREIGN KEY (project_id)
        REFERENCES public.project (project_id)
        ON DELETE CASCADE,
    CONSTRAINT project_category_category_fk
        FOREIGN KEY (category_id)
        REFERENCES public.category (category_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS project_category_category_id_idx
    ON public.project_category (category_id);

INSERT INTO public.project_category (
    project_id,
    category_id
)
SELECT p.project_id, c.category_id
FROM (
    VALUES
        ('Community Center Painting', 'Construction'),
        ('Community Center Painting', 'Community Support'),
        ('Senior Home Ramp Build', 'Construction'),
        ('Senior Home Ramp Build', 'Community Support'),
        ('Playground Repair Day', 'Construction'),
        ('Playground Repair Day', 'Community Support'),
        ('Shelter Storage Shelves', 'Construction'),
        ('Shelter Storage Shelves', 'Community Support'),
        ('Trail Kiosk Installation', 'Construction'),
        ('Trail Kiosk Installation', 'Environment'),
        ('Neighborhood Garden Prep', 'Environment'),
        ('Neighborhood Garden Prep', 'Food Security'),
        ('Harvest Box Assembly', 'Food Security'),
        ('School Garden Workshop', 'Education'),
        ('School Garden Workshop', 'Environment'),
        ('Compost Education Booth', 'Education'),
        ('Compost Education Booth', 'Environment'),
        ('Orchard Gleaning Morning', 'Food Security'),
        ('Orchard Gleaning Morning', 'Community Support'),
        ('Food Pantry Sorting', 'Food Security'),
        ('Food Pantry Sorting', 'Community Support'),
        ('Backpack Supply Drive', 'Education'),
        ('Backpack Supply Drive', 'Community Support'),
        ('Community Tutoring Night', 'Education'),
        ('Charity 5K Volunteer Crew', 'Community Support'),
        ('Winter Clothing Collection', 'Community Support')
) AS project_categories(project_title, category_name)
JOIN public.project p
    ON p.title = project_categories.project_title
JOIN public.category c
    ON c.name = project_categories.category_name
ON CONFLICT (project_id, category_id) DO NOTHING;
